In [1]:
import pandas as pd
import numpy as np
import re
%matplotlib inline

In [2]:
data = pd.read_csv("data.csv")

In [3]:
data.head(15)

,Unnamed: 0,2016,2016.1,2016.2,2015,2015.1,2015.2,2014,2014.1,2014.2,...,1978.2,1977,1977.1,1977.2,1976,1976.1,1976.2,1975,1975.1,1975.2
0,NaN,"Prevalence of obesity among adults, BMI &Great...","Prevalence of obesity among adults, BMI &Great...","Prevalence of obesity among adults, BMI &Great...","Prevalence of obesity among adults, BMI &Great...","Prevalence of obesity among adults, BMI &Great...","Prevalence of obesity among adults, BMI &Great...","Prevalence of obesity among adults, BMI &Great...","Prevalence of obesity among adults, BMI &Great...","Prevalence of obesity among adults, BMI &Great...",...,"Prevalence of obesity among adults, BMI &Great...","Prevalence of obesity among adults, BMI &Great...","Prevalence of obesity among adults, BMI &Great...","Prevalence of obesity among adults, BMI &Great...","Prevalence of obesity among adults, BMI &Great...","Prevalence of obesity among adults, BMI &Great...","Prevalence of obesity among adults, BMI &Great...","Prevalence of obesity among adults, BMI &Great...","Prevalence of obesity among adults, BMI &Great...","Prevalence of obesity among adults, BMI &Great..."
1,NaN,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years,...,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years
2,Country,Both sexes,Male,Female,Both sexes,Male,Female,Both sexes,Male,Female,...,Female,Both sexes,Male,Female,Both sexes,Male,Female,Both sexes,Male,Female
3,Afghanistan,5.5 [3.4-8.1],3.2 [1.3-6.4],7.6 [4.3-12.4],5.2 [3.3-7.7],3.0 [1.3-6.0],7.3 [4.1-11.8],4.9 [3.1-7.3],2.8 [1.2-5.6],7.0 [4.0-11.3],...,0.9 [0.3-2.2],0.6 [0.2-1.2],0.2 [0.0-0.7],0.9 [0.3-2.1],0.5 [0.2-1.1],0.2 [0.0-0.7],0.8 [0.2-2.0],0.5 [0.2-1.1],0.2 [0.0-0.6],0.8 [0.2-2.0]
4,Albania,21.7 [17.0-26.7],21.6 [14.8-29.0],21.8 [15.3-28.9],21.1 [16.6-26.0],20.9 [14.4-28.1],21.3 [15.1-28.1],20.5 [16.2-25.1],20.2 [13.9-27.3],20.8 [14.9-27.4],...,9.1 [4.6-15.5],6.8 [4.0-10.7],4.8 [2.0-9.3],8.9 [4.3-15.4],6.7 [3.8-10.6],4.6 [1.8-9.2],8.8 [4.1-15.4],6.5 [3.6-10.5],4.4 [1.7-9.2],8.6 [3.9-15.4]
5,Algeria,27.4 [22.5-32.7],19.9 [13.6-27.1],34.9 [27.6-42.7],26.7 [21.9-31.8],19.2 [13.2-26.1],34.2 [27.1-41.7],26.0 [21.4-30.9],18.5 [12.7-25.0],33.6 [26.7-40.7],...,11.8 [6.5-18.6],7.4 [4.3-11.3],3.1 [1.2-6.2],11.4 [6.2-18.4],7.2 [4.1-11.1],2.9 [1.1-6.1],11.1 [5.8-18.2],6.9 [3.9-10.9],2.8 [1.0-6.0],10.7 [5.5-18.0]
6,Andorra,25.6 [20.1-31.3],25.9 [18.0-34.3],25.3 [17.7-33.7],25.4 [20.1-31.0],25.5 [17.8-33.8],25.2 [17.7-33.4],25.2 [20.0-30.7],25.2 [17.6-33.3],25.1 [17.8-33.1],...,17.5 [10.9-25.3],14.0 [9.6-19.1],10.7 [5.6-17.4],16.9 [10.4-24.8],13.5 [9.1-18.6],10.2 [5.2-16.9],16.4 [9.8-24.4],12.9 [8.6-18.1],9.7 [4.7-16.3],15.8 [9.2-23.9]
7,Angola,8.2 [5.1-12.2],4.0 [1.6-7.9],12.1 [6.8-19.0],7.9 [4.9-11.7],3.8 [1.5-7.3],11.6 [6.5-18.2],7.5 [4.7-11.2],3.6 [1.4-6.9],11.1 [6.2-17.5],...,1.6 [0.5-3.7],0.9 [0.3-2.0],0.3 [0.0-0.9],1.5 [0.4-3.6],0.9 [0.3-2.0],0.3 [0.0-0.9],1.4 [0.4-3.5],0.8 [0.3-1.9],0.2 [0.0-0.8],1.4 [0.4-3.4]
8,Antigua and Barbuda,18.9 [13.8-24.6],11.6 [6.4-18.6],25.9 [17.6-35.2],18.4 [13.5-23.8],11.2 [6.2-17.8],25.3 [17.3-34.3],18.0 [13.2-23.1],10.8 [6.1-17.1],24.8 [17.1-33.5],...,9.6 [5.0-16.1],6.0 [3.4-9.5],2.5 [0.9-5.4],9.3 [4.7-15.9],5.8 [3.2-9.3],2.4 [0.8-5.3],9.1 [4.4-15.7],5.6 [3.0-9.1],2.3 [0.8-5.1],8.8 [4.1-15.6]
9,Argentina,28.3 [23.4-33.5],27.3 [20.5-35.0],29.0 [22.5-36.0],27.8 [23.2-32.7],26.8 [20.2-34.1],28.5 [22.3-35.1],27.3 [22.9-32.0],26.2 [20.0-33.1],28.1 [22.1-34.4],...,14.1 [9.0-20.5],11.8 [8.2-16.0],9.6 [5.2-15.4],13.8 [8.6-20.3],11.5 [7.8-15.8],9.3 [4.9-15.3],13.5 [8.1-20.2],11.2 [7.5-15.7],9.0 [4.6-15.2],13.2 [7.7-20.1]
10,Armenia,20.2 [15.7-24.8],17.1 [11.1-24.0],23.0 [16.6-29.9],19.7 [15.4-24.2],16.6 [10.9-23.3],22.6 [16.4-29.1],19.2 [15.1-23.6],16.1 [10.6-22.7],22.1 [16.1-28.3],...,10.5 [5.7-16.9],7.9 [4.8-11.9],4.9 [2.0-9.3],10.2 [5.3-16.7],7.6 [4.5-11.7],4.7 [1.8-9.1],9.8 [5.0-16.5],7.3 [4.2-11.5],4.5 [1.7-8.9],9.5 [4.7-16.2]
11,Australia,29.0 [25.3-32.9],29.6 [24.2-35.3],28.4 [23.1-33.9],28.4 [24.9-32.1],28.9 [23.9-34.3],27.9 [23.0-33.1],27.9 [24.6-31.4],28.3 [23.6-33.4],27.4 [22.8-32.2],...,12.0 [8.7-15.7],11.0 [8.6-13.8],10.3 [7.0-14.1],11.7 [8.3-15.6],10.8 [8.2-13.5],10.0 [6.6-14.0],11.5 [8.0-15.4],10.5 [7.9-13.4],9.7 [6.2-13.9],11.2 [7.6-15.2]
12,Austria,20.1 [15.9-24.6],21.9 [15.6-29.0],18.3 [12.9-24.4],19.7 [15.6-23.9],21.3 [15.4-28.1],18.0 [12.8-23.8],19.2 [15.4-23.3],20.8 [15.2-27.3],17.7 [12.7-23.1],...,8.2 [5.2-12.0],7.5 [5.3-10.2],6.7 [3.8-10.7],8.1 [5.0-11.9],7.3 [5.1-10.0],6.5 [3.6-10.4],7.9 [4.8-11.8],7.2 [4.9-9.9],6.3 [3.4-10.4],7.8 [4.6-11.7]
13,Azerbaijan,19.9 [15.3-24.9],15.8 [9.9-22.9],23.6 [16.7-31.0],19.3 [14.9-24.1],15.3 [9.5-22.0],23.0 [16.5-30.2],18.8 [14.5-23.5],14.7 [9.2-21.2],22.4 [16.2-29.3],...,9.2 [4.6-15.5],6.8 [3.9-10.7],4.0 [1.5-8.1],8.9 [4.3-15.4],6.6 [3.7-10.5],3.9 [1.4-8.0],8.7 [4.1-15.2],6.4 [3.5-10.4],3.7 [1.3-7.9],8.4 [3.9-15.1]
14,Bahamas,31.6 [25.6-37.8],24.4 [16.2-33.4],38.1 [29.0-47.3],31.0 [25.2-37.1],23.8 [16.0-32.3],37.6 [28.8-46.6],30.5 [24.8-36.4],23.2 [15.7-31.4],37.2 [28.6-45.9],...,19.2 [11.9-27.8],12.8 [8.5-18.0],6.3 [2.8-11.3],18.7 [11.2-27.4],12.4 [8.1-17.8],6.0 [2.6-11.0],18.2 [10.7-27.0],12.0 [7.6-17.4],5.7 [2.3-10.7],17.7 [10.2-26.6]

In [4]:
data.iloc[0,1]

'Prevalence of obesity among adults, BMI &GreaterEqual; 30 (age-standardized estimate) (%)'

In [5]:
data.shape

(198, 127)

In [6]:
data.dropna(inplace=True)
data.drop([2],inplace=True)
data.shape

(195, 127)

In [7]:
data.head()

,Unnamed: 0,2016,2016.1,2016.2,2015,2015.1,2015.2,2014,2014.1,2014.2,...,1978.2,1977,1977.1,1977.2,1976,1976.1,1976.2,1975,1975.1,1975.2
3,Afghanistan,5.5 [3.4-8.1],3.2 [1.3-6.4],7.6 [4.3-12.4],5.2 [3.3-7.7],3.0 [1.3-6.0],7.3 [4.1-11.8],4.9 [3.1-7.3],2.8 [1.2-5.6],7.0 [4.0-11.3],...,0.9 [0.3-2.2],0.6 [0.2-1.2],0.2 [0.0-0.7],0.9 [0.3-2.1],0.5 [0.2-1.1],0.2 [0.0-0.7],0.8 [0.2-2.0],0.5 [0.2-1.1],0.2 [0.0-0.6],0.8 [0.2-2.0]
4,Albania,21.7 [17.0-26.7],21.6 [14.8-29.0],21.8 [15.3-28.9],21.1 [16.6-26.0],20.9 [14.4-28.1],21.3 [15.1-28.1],20.5 [16.2-25.1],20.2 [13.9-27.3],20.8 [14.9-27.4],...,9.1 [4.6-15.5],6.8 [4.0-10.7],4.8 [2.0-9.3],8.9 [4.3-15.4],6.7 [3.8-10.6],4.6 [1.8-9.2],8.8 [4.1-15.4],6.5 [3.6-10.5],4.4 [1.7-9.2],8.6 [3.9-15.4]
5,Algeria,27.4 [22.5-32.7],19.9 [13.6-27.1],34.9 [27.6-42.7],26.7 [21.9-31.8],19.2 [13.2-26.1],34.2 [27.1-41.7],26.0 [21.4-30.9],18.5 [12.7-25.0],33.6 [26.7-40.7],...,11.8 [6.5-18.6],7.4 [4.3-11.3],3.1 [1.2-6.2],11.4 [6.2-18.4],7.2 [4.1-11.1],2.9 [1.1-6.1],11.1 [5.8-18.2],6.9 [3.9-10.9],2.8 [1.0-6.0],10.7 [5.5-18.0]
6,Andorra,25.6 [20.1-31.3],25.9 [18.0-34.3],25.3 [17.7-33.7],25.4 [20.1-31.0],25.5 [17.8-33.8],25.2 [17.7-33.4],25.2 [20.0-30.7],25.2 [17.6-33.3],25.1 [17.8-33.1],...,17.5 [10.9-25.3],14.0 [9.6-19.1],10.7 [5.6-17.4],16.9 [10.4-24.8],13.5 [9.1-18.6],10.2 [5.2-16.9],16.4 [9.8-24.4],12.9 [8.6-18.1],9.7 [4.7-16.3],15.8 [9.2-23.9]
7,Angola,8.2 [5.1-12.2],4.0 [1.6-7.9],12.1 [6.8-19.0],7.9 [4.9-11.7],3.8 [1.5-7.3],11.6 [6.5-18.2],7.5 [4.7-11.2],3.6 [1.4-6.9],11.1 [6.2-17.5],...,1.6 [0.5-3.7],0.9 [0.3-2.0],0.3 [0.0-0.9],1.5 [0.4-3.6],0.9 [0.3-2.0],0.3 [0.0-0.9],1.4 [0.4-3.5],0.8 [0.3-1.9],0.2 [0.0-0.8],1.4 [0.4-3.4]

In [8]:
data.reset_index(drop=True,inplace=True)
data.head()

,Unnamed: 0,2016,2016.1,2016.2,2015,2015.1,2015.2,2014,2014.1,2014.2,...,1978.2,1977,1977.1,1977.2,1976,1976.1,1976.2,1975,1975.1,1975.2
0,Afghanistan,5.5 [3.4-8.1],3.2 [1.3-6.4],7.6 [4.3-12.4],5.2 [3.3-7.7],3.0 [1.3-6.0],7.3 [4.1-11.8],4.9 [3.1-7.3],2.8 [1.2-5.6],7.0 [4.0-11.3],...,0.9 [0.3-2.2],0.6 [0.2-1.2],0.2 [0.0-0.7],0.9 [0.3-2.1],0.5 [0.2-1.1],0.2 [0.0-0.7],0.8 [0.2-2.0],0.5 [0.2-1.1],0.2 [0.0-0.6],0.8 [0.2-2.0]
1,Albania,21.7 [17.0-26.7],21.6 [14.8-29.0],21.8 [15.3-28.9],21.1 [16.6-26.0],20.9 [14.4-28.1],21.3 [15.1-28.1],20.5 [16.2-25.1],20.2 [13.9-27.3],20.8 [14.9-27.4],...,9.1 [4.6-15.5],6.8 [4.0-10.7],4.8 [2.0-9.3],8.9 [4.3-15.4],6.7 [3.8-10.6],4.6 [1.8-9.2],8.8 [4.1-15.4],6.5 [3.6-10.5],4.4 [1.7-9.2],8.6 [3.9-15.4]
2,Algeria,27.4 [22.5-32.7],19.9 [13.6-27.1],34.9 [27.6-42.7],26.7 [21.9-31.8],19.2 [13.2-26.1],34.2 [27.1-41.7],26.0 [21.4-30.9],18.5 [12.7-25.0],33.6 [26.7-40.7],...,11.8 [6.5-18.6],7.4 [4.3-11.3],3.1 [1.2-6.2],11.4 [6.2-18.4],7.2 [4.1-11.1],2.9 [1.1-6.1],11.1 [5.8-18.2],6.9 [3.9-10.9],2.8 [1.0-6.0],10.7 [5.5-18.0]
3,Andorra,25.6 [20.1-31.3],25.9 [18.0-34.3],25.3 [17.7-33.7],25.4 [20.1-31.0],25.5 [17.8-33.8],25.2 [17.7-33.4],25.2 [20.0-30.7],25.2 [17.6-33.3],25.1 [17.8-33.1],...,17.5 [10.9-25.3],14.0 [9.6-19.1],10.7 [5.6-17.4],16.9 [10.4-24.8],13.5 [9.1-18.6],10.2 [5.2-16.9],16.4 [9.8-24.4],12.9 [8.6-18.1],9.7 [4.7-16.3],15.8 [9.2-23.9]
4,Angola,8.2 [5.1-12.2],4.0 [1.6-7.9],12.1 [6.8-19.0],7.9 [4.9-11.7],3.8 [1.5-7.3],11.6 [6.5-18.2],7.5 [4.7-11.2],3.6 [1.4-6.9],11.1 [6.2-17.5],...,1.6 [0.5-3.7],0.9 [0.3-2.0],0.3 [0.0-0.9],1.5 [0.4-3.6],0.9 [0.3-2.0],0.3 [0.0-0.9],1.4 [0.4-3.5],0.8 [0.3-1.9],0.2 [0.0-0.8],1.4 [0.4-3.4]

In [9]:
data.rename(columns={'Unnamed: 0': 'Country'}, inplace=True)
data.head()

,Country,2016,2016.1,2016.2,2015,2015.1,2015.2,2014,2014.1,2014.2,...,1978.2,1977,1977.1,1977.2,1976,1976.1,1976.2,1975,1975.1,1975.2
0,Afghanistan,5.5 [3.4-8.1],3.2 [1.3-6.4],7.6 [4.3-12.4],5.2 [3.3-7.7],3.0 [1.3-6.0],7.3 [4.1-11.8],4.9 [3.1-7.3],2.8 [1.2-5.6],7.0 [4.0-11.3],...,0.9 [0.3-2.2],0.6 [0.2-1.2],0.2 [0.0-0.7],0.9 [0.3-2.1],0.5 [0.2-1.1],0.2 [0.0-0.7],0.8 [0.2-2.0],0.5 [0.2-1.1],0.2 [0.0-0.6],0.8 [0.2-2.0]
1,Albania,21.7 [17.0-26.7],21.6 [14.8-29.0],21.8 [15.3-28.9],21.1 [16.6-26.0],20.9 [14.4-28.1],21.3 [15.1-28.1],20.5 [16.2-25.1],20.2 [13.9-27.3],20.8 [14.9-27.4],...,9.1 [4.6-15.5],6.8 [4.0-10.7],4.8 [2.0-9.3],8.9 [4.3-15.4],6.7 [3.8-10.6],4.6 [1.8-9.2],8.8 [4.1-15.4],6.5 [3.6-10.5],4.4 [1.7-9.2],8.6 [3.9-15.4]
2,Algeria,27.4 [22.5-32.7],19.9 [13.6-27.1],34.9 [27.6-42.7],26.7 [21.9-31.8],19.2 [13.2-26.1],34.2 [27.1-41.7],26.0 [21.4-30.9],18.5 [12.7-25.0],33.6 [26.7-40.7],...,11.8 [6.5-18.6],7.4 [4.3-11.3],3.1 [1.2-6.2],11.4 [6.2-18.4],7.2 [4.1-11.1],2.9 [1.1-6.1],11.1 [5.8-18.2],6.9 [3.9-10.9],2.8 [1.0-6.0],10.7 [5.5-18.0]
3,Andorra,25.6 [20.1-31.3],25.9 [18.0-34.3],25.3 [17.7-33.7],25.4 [20.1-31.0],25.5 [17.8-33.8],25.2 [17.7-33.4],25.2 [20.0-30.7],25.2 [17.6-33.3],25.1 [17.8-33.1],...,17.5 [10.9-25.3],14.0 [9.6-19.1],10.7 [5.6-17.4],16.9 [10.4-24.8],13.5 [9.1-18.6],10.2 [5.2-16.9],16.4 [9.8-24.4],12.9 [8.6-18.1],9.7 [4.7-16.3],15.8 [9.2-23.9]
4,Angola,8.2 [5.1-12.2],4.0 [1.6-7.9],12.1 [6.8-19.0],7.9 [4.9-11.7],3.8 [1.5-7.3],11.6 [6.5-18.2],7.5 [4.7-11.2],3.6 [1.4-6.9],11.1 [6.2-17.5],...,1.6 [0.5-3.7],0.9 [0.3-2.0],0.3 [0.0-0.9],1.5 [0.4-3.6],0.9 [0.3-2.0],0.3 [0.0-0.9],1.4 [0.4-3.5],0.8 [0.3-1.9],0.2 [0.0-0.8],1.4 [0.4-3.4]

In [10]:
data_melt = data.melt(id_vars=['Country'],var_name='Year',value_name='Obesity(%)')

In [11]:
data_melt[['Year','Sex']] = data_melt['Year'].str.split(".", expand=True)
data_melt.head()

       Country  Year        Obesity(%)   Sex
0  Afghanistan  2016     5.5 [3.4-8.1]  None
1      Albania  2016  21.7 [17.0-26.7]  None
2      Algeria  2016  27.4 [22.5-32.7]  None
3      Andorra  2016  25.6 [20.1-31.3]  None
4       Angola  2016    8.2 [5.1-12.2]  None

<p>Splitting the data into Male, Female and Both Sexes

In [12]:
data_melt["Sex"] = data_melt["Sex"].map({None:'Both Sexes','1':'Male','2':'Female'})
data_melt[data_melt['Country']=="Albania"]

       Country  Year        Obesity(%)         Sex
1      Albania  2016  21.7 [17.0-26.7]  Both Sexes
196    Albania  2016  21.6 [14.8-29.0]        Male
391    Albania  2016  21.8 [15.3-28.9]      Female
586    Albania  2015  21.1 [16.6-26.0]  Both Sexes
781    Albania  2015  20.9 [14.4-28.1]        Male
...        ...   ...               ...         ...
23596  Albania  1976     4.6 [1.8-9.2]        Male
23791  Albania  1976    8.8 [4.1-15.4]      Female
23986  Albania  1975    6.5 [3.6-10.5]  Both Sexes
24181  Albania  1975     4.4 [1.7-9.2]        Male
24376  Albania  1975    8.6 [3.9-15.4]      Female

[126 rows x 4 columns]

<B>The copy method is used as an error can occur as pandas may return a view and not a copy

In [13]:
male_data = data_melt[data_melt.Sex == 'Male'].copy()
male_data.drop(['Sex'],axis=1,inplace=True)
female_data = data_melt[data_melt.Sex == 'Female'].copy()
female_data.drop(['Sex'],axis=1,inplace=True)
both_data = data_melt[data_melt.Sex == 'Both Sexes'].copy()
both_data.drop(['Sex'],axis=1,inplace=True)

In [14]:
male_data

                                  Country  Year        Obesity(%)
195                           Afghanistan  2016     3.2 [1.3-6.4]
196                               Albania  2016  21.6 [14.8-29.0]
197                               Algeria  2016  19.9 [13.6-27.1]
198                               Andorra  2016  25.9 [18.0-34.3]
199                                Angola  2016     4.0 [1.6-7.9]
...                                   ...   ...               ...
24370  Venezuela (Bolivarian Republic of)  1975    5.9 [2.7-11.2]
24371                            Viet Nam  1975     0.1 [0.0-0.2]
24372                               Yemen  1975     1.2 [0.3-3.1]
24373                              Zambia  1975     0.5 [0.1-1.4]
24374                            Zimbabwe  1975     0.4 [0.1-1.3]

[8190 rows x 3 columns]

In [15]:
male_data[male_data['Country']=='United States of America']

                        Country  Year        Obesity(%)
381    United States of America  2016  35.5 [30.0-41.2]
966    United States of America  2015  34.7 [29.7-40.1]
1551   United States of America  2014  34.0 [29.2-39.0]
2136   United States of America  2013  33.3 [28.8-38.0]
2721   United States of America  2012  32.6 [28.3-37.1]
3306   United States of America  2011  31.9 [27.8-36.2]
3891   United States of America  2010  31.2 [27.4-35.3]
4476   United States of America  2009  30.5 [26.8-34.5]
5061   United States of America  2008  29.8 [26.2-33.6]
5646   United States of America  2007  29.1 [25.6-32.9]
6231   United States of America  2006  28.4 [24.9-32.2]
6816   United States of America  2005  27.7 [24.2-31.4]
7401   United States of America  2004  27.0 [23.5-30.7]
7986   United States of America  2003  26.3 [22.8-29.9]
8571   United States of America  2002  25.5 [22.0-29.2]
9156   United States of America  2001  24.8 [21.3-28.5]
9741   United States of America  2000  24.0 [20.6-27.8]
10326  United States of America  1999  23.3 [19.8-27.1]
10911  United States of America  1998  22.5 [19.0-26.3]
11496  United States of America  1997  21.8 [18.3-25.5]
12081  United States of America  1996  21.0 [17.6-24.8]
12666  United States of America  1995  20.3 [16.9-24.0]
13251  United States of America  1994  19.6 [16.2-23.3]
13836  United States of America  1993  18.9 [15.6-22.6]
14421  United States of America  1992  18.3 [15.0-21.9]
15006  United States of America  1991  17.6 [14.4-21.3]
15591  United States of America  1990  17.0 [13.8-20.6]
16176  United States of America  1989  16.4 [13.3-20.0]
16761  United States of America  1988  15.9 [12.7-19.4]
17346  United States of America  1987  15.3 [12.2-18.8]
17931  United States of America  1986  14.8 [11.7-18.3]
18516  United States of America  1985  14.3 [11.3-17.8]
19101  United States of America  1984  13.8 [10.8-17.3]
19686  United States of America  1983  13.4 [10.3-16.9]
20271  United States of America  1982   12.9 [9.9-16.6]
20856  United States of America  1981   12.5 [9.4-16.2]
21441  United States of America  1980   12.1 [9.0-15.8]
22026  United States of America  1979   11.7 [8.6-15.5]
22611  United States of America  1978   11.4 [8.2-15.3]
23196  United States of America  1977   11.0 [7.8-15.0]
23781  United States of America  1976   10.7 [7.4-14.7]
24366  United States of America  1975   10.3 [7.0-14.5]

In [16]:
pat = re.compile(r'[0-9]{0,1}\d\.{1,2}\d')
x = re.match('\d\d\.[\d\d]','11.0[1-2-3]')

In [19]:
male_data["Obesity(%)"]=male_data['Obesity(%)'].apply(lambda x:re.sub('\[.*','',x))

In [20]:
male_data

                                  Country  Year Obesity(%)
195                           Afghanistan  2016       3.2
196                               Albania  2016      21.6
197                               Algeria  2016      19.9
198                               Andorra  2016      25.9
199                                Angola  2016       4.0
...                                   ...   ...        ...
24370  Venezuela (Bolivarian Republic of)  1975       5.9
24371                            Viet Nam  1975       0.1
24372                               Yemen  1975       1.2
24373                              Zambia  1975       0.5
24374                            Zimbabwe  1975       0.4

[8190 rows x 3 columns]